name: esdok
services:
  backend:
    build: backend/
    volumes:
      - /app/res/
    ports:
      - 8030:5000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  frontend:
    build: frontend/
    ports:
      - 8031:80
